config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  # Devise & Product CRUD routes
  #
  devise_for :users
  resources :products

  # Custom routes for user account, payment results & webhook
  #
  get '/account/', to: 'pages#account', as: 'show_current_account'
  get '/payments/success', to: 'payments#success', as: 'success_payment'
  get '/payments/failure', to: 'payments#failure', as: 'failure_payment'
  post '/payments/webhook', to: 'payments#webhook'
end

app/views/shared/_footer.html.erb
<div class="footer">
    <div class="col-md-12">
        <p>Made by Max @ <a href="maxPiroddi.github.com" target="_blank">GitHub</a></p>
        <p>Built with Ruby on Rails, styled with Bootstrap.</p>
    </div>
</div>

app/views/shared/_topnav.html.erb
<nav class="navbar navbar-light">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to("Musos Market", root_path, class: "navbar-brand") %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to("Sign Out", destroy_user_session_path, method: :delete) %></li>
              <li><%= link_to("New Listing", new_product_path) %></li>
            <% else %>
              <li><%= link_to("Sign Up", new_user_registration_path, class: "nav-item nav-link") %></li>
              <li><%= link_to("Log In", new_user_session_path, class: "nav-item nav-link") %></li>
            <% end %>
          </ul>

          <form class="navbar-form navbar-left" action="<%= products_path %>" method="GET">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search..." name="search">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
          </form>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to("My Account", show_current_account_path) %>
            <% end %>
          </ul>
        </div>
</nav>