config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  # Devise & Product CRUD routes
  #
  devise_for :users
  resources :products

  # Custom routes for user account, payment results & webhook
  #
  get '/account/', to: 'pages#account', as: 'show_current_account'
  get '/payments/success', to: 'payments#success', as: 'success_payment'
  get '/payments/failure', to: 'payments#failure', as: 'failure_payment'
  post '/payments/webhook', to: 'payments#webhook'
end

app/views/pages/_account_products.html.erb
<div class="row">
    <h3>Current Listings</h3>
    <% @account.products.where("purchased = false").each do |product| %>
        <div class="col-sm-6 col-md-4 listing-box">
            <div class="thumbnail account-card">
                <%= image_tag((product.picture if product.picture.attached?), class: "account-img")%>
                <div class="caption">
                    <h3><%= product.name %></h3>
                    <h5>Price: <%= number_to_currency(product.price / 100) %></h5>
                    <h5>Condition: <%= product.condition.name %></h5>
                    <div class="account-button-container">
                        <%= link_to("View", product_path(product), class: "btn btn-default") %>
                        <%= link_to("Edit", edit_product_path(product), class: "btn btn-default") %>
                        <%= link_to("Delete", product_path(product), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default") %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

<div class="row">
    <h3>Sold Items</h3>
    <% @account.products.where("purchased = true").each do |product| %>
        <div class="col-sm-6 col-md-4 listing-box">
            <div class="thumbnail account-card">
                <%= image_tag((product.picture if product.picture.attached?), class: "account-img")%>
                <div class="caption">
                    <h3><%= product.name %></h3>
                    <h5>Price: <%= number_to_currency(product.price / 100) %></h5>
                    <h5>Condition: <%= product.condition.name %></h5>
                </div>
            </div>
        </div>
    <% end %>
</div>

<div class="row">
    <h3>Purchased Items</h3>
    <% @purchase.each do |bought| %>
        <div class="col-sm-6 col-md-4 listing-box">
            <div class="thumbnail account-card">
                <%= image_tag((bought.product.picture if bought.product.picture.attached?), class: "account-img")%>
                <div class="caption">
                    <h3><%= bought.product.name %></h3>
                    <h5>Price: <%= number_to_currency(bought.product.price / 100) %></h5>
                    <h5>Condition: <%= bought.product.condition.name %></h5>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/pages/_categories.html.erb
<div class="col-md-4">
    <%= link_to(products_path + "?category_id=1") do %>
        <div class="card category-card">
          <div class="card-body">
            <%= image_tag "category-icons/guitar.svg", alt: "Guitar Logo", class: "category-logo" %>
            <h5 class="card-title">Guitars</h5>
          </div>
        </div>
    <% end %>
</div>
<div class="col-md-4">
    <%= link_to(products_path + "?category_id=2") do %>
        <div class="card category-card">
          <div class="card-body">
            <%= image_tag "category-icons/bass.svg", alt: "Bass Logo", class: "category-logo" %>
            <h5 class="card-title">Bass Guitars</h5>
          </div>
        </div>
    <% end %>
</div>
<div class="col-md-4">
    <%= link_to(products_path + "?category_id=3") do %>
        <div class="card category-card">
            <div class="card-body">
                <%= image_tag "category-icons/drum.svg", alt: "Drum Logo", class: "category-logo" %>
                <h5 class="card-title">Drums & Percussion</h5>
            </div>
        </div>
    <% end %>
</div>
<div class="col-md-4">
    <%= link_to(products_path + "?category_id=4") do %>
        <div class="card category-card">
            <div class="card-body">
                <%= image_tag "category-icons/synth.svg", alt: "Synth Logo", class: "category-logo" %>
                <h5 class="card-title">Synths & Keyboards</h5>
            </div>
        </div>
    <% end %>
</div>
<div class="col-md-4">
    <%= link_to(products_path + "?category_id=5") do %>
        <div class="card category-card">
            <div class="card-body">
                <%= image_tag "category-icons/amp.svg", alt: "Amp Logo", class: "category-logo" %>
                <h5 class="card-title">Amplifiers</h5>
            </div>
        </div>
    <% end %>
</div>
<div class="col-md-4">
    <%= link_to(products_path + "?category_id=6") do %>
        <div class="card category-card">
            <div class="card-body">
                <%= image_tag "category-icons/pro-audio.svg", alt: "Pro Audio Logo", class: "category-logo" %>
                <h5 class="card-title">Pro Audio</h5>
            </div>
        </div>
    <% end %>
</div>

app/views/pages/account.html.erb
<%= render("shared/topnav") %>

<div class="container">
    <div class=".col-xs-6 .col-md-6 account-box">
        <div class="account-name">
            <p id="notice"><%= notice %></p>

            <h1 id="account-title">Hello <%= @account.name.split.first %>!</h1>
        </div>
        <div class="account-details">
            <p>Email: <%= @account.email %></p>
            <p>Postcode: <%= @account.postcode %></p>
            <p><%= link_to "Edit details", edit_user_registration_path %></p>
        </div>
    </div>



    <%= render("account_products") %>
</div>

<%= render("shared/footer") %>

app/views/pages/home.html.erb
<%= render("shared/topnav")%>

<div class="container">
    <p id="notice"><%= notice %></p>
    <div class="jumbotron">
        <h2 class="display-4">Let's find something great!</h2>
        <%= form_with url: products_path, method: "GET", local: true do |form| %>
            <%= form.text_field :search, class: "form-control", id: "hero-search", placeholder: "Search..." %>
        <% end %>
        <p class="random-product"><%= link_to("View All Listings", products_path) %></p>
        <p class="random-product"><%= link_to("Maybe try '#{@random_product.name}'", product_path(@random_product)) %></p>
    </div>
    <div class="category-box">
        <h2 class="display-4">Shop by Category</h2>
    </div>

    <div class="row category-row">
        <%= render("categories") %>
    </div>
</div>

<%= render("shared/footer") %>